# Generated by Django 2.1 on 2018-08-20 13:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('table', models.IntegerField()),
                ('visitors', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('contact_telephone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+380\\d{9}$', "Phone number must be entered in the format: '+380xxxxxxxxx'.")])),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('number_tables', models.IntegerField(validators=[django.core.validators.MinValueValidator(5)])),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+380\\d{9}$', "Phone number must be entered in the format: '+380xxxxxxxxx'.")])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.Restaurant'),
        ),
    ]
