# Generated by Django 2.1 on 2018-08-21 08:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('table', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitors', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('contact_telephone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+380\\d{9}$', "Phone number must be entered in the format: '+380xxxxxxxxx'.")])),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('number_tables', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('open_time', models.CharField(max_length=5)),
                ('close_time', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'restaurants',
                'verbose_name': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('numb', models.PositiveSmallIntegerField()),
                ('count_sits', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.Restaurant'),
        ),
    ]
