# Generated by Django 2.1 on 2018-08-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_restaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status_user',
            field=models.CharField(choices=[('usr', 'Client'), ('rst_adm', 'Restaurant admin')], default='usr', max_length=20),
        ),
    ]
