# Generated by Django 2.1 on 2018-08-29 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20180827_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_order', models.BooleanField(null=True)),
                ('reservations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
