# Generated by Django 2.1 on 2018-08-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180827_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
